[package]
name = "e1000-driver"
authors = ["Luoyuan Xiao <xiaoluoyuan@163.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.3.0"
log = "0.4"
